import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import request from "supertest";
import { createKernelApp } from "../server/app.js";

test("outdoor discovery denies internal endpoints, secrets, rotation reuse and revoked credentials", async t => {
  const directory = mkdtempSync(path.join(os.tmpdir(), "kernel-outdoor-"));
  let secret = false;
  const ref = "volt://33333333-3333-4333-8333-333333333333/1";
  const app = createKernelApp({ dataDir: directory, defaultsDir: path.resolve("data/defaults"), distDir: path.join(directory, "none"), accessKey: "operator", sessionSecret: "s".repeat(40), apiToken: "legacy-" + "a".repeat(32), diskPath: directory, voltClient: { async resolve(references) { return { schema: "volt.resolve.v1", resolution_revision: "v1", values: Object.fromEntries(references.map(value => [value, { value: "saturn.example.org", visibility: secret ? "secret" : "plain", revision: 1 }])) }; } }, serviceStatusFetch: async () => { throw Error("offline fixture"); } });
  t.after(() => { app.locals.kernel.close(); rmSync(directory, { recursive: true, force: true }); });
  app.locals.kernel.store.upsertRegisterEntries([{ key: "services.saturn.sni", value: ref, description: "Saturn" }, { key: "repositories.volt.url", value: ref, description: "Forbidden alias" }], "test", { replace: true });
  const operator = request.agent(app);
  await operator.post("/api/auth/login").send({ access_key: "operator" });
  assert.equal((await request(app).post("/api/outdoor-tokens").send({ name: "Server" })).status, 401);
  const created = await operator.post("/api/outdoor-tokens").send({ name: "External config host" });
  assert.equal(created.status, 201);
  const { token, id } = created.body;
  const resolve = (credential, keys) => request(app).post("/api/v1/register/resolve").set("Authorization", "Bearer " + credential).send({ keys });
  assert.equal((await resolve(token, ["services.saturn.sni"])).status, 200);
  assert.equal((await resolve(token, ["repositories.volt.url"])).status, 403);
  for (const endpoint of ["register/snapshot", "register/sections/services", "register/resolve?key=services.saturn.sni", "constitution/raw", "constitution/snapshot", "constitution/meta"]) assert.equal((await request(app).get("/api/v1/" + endpoint).set("Authorization", "Bearer " + token)).status, 403);
  assert.equal((await request(app).get("/api/outdoor-tokens").set("Authorization", "Bearer " + token)).status, 403);
  secret = true;
  assert.equal((await resolve(token, ["services.saturn.sni"])).status, 403);
  secret = false;
  assert.equal(JSON.stringify((await operator.get("/api/outdoor-tokens")).body).includes(token), false);
  assert.equal(JSON.stringify(app.locals.kernel.store.exportBackup()).includes(token), false);
  const rotated = await operator.post(`/api/outdoor-tokens/${id}/rotate`).send({});
  assert.equal(rotated.status, 200);
  assert.equal((await resolve(token, ["services.saturn.sni"])).status, 401);
  assert.equal((await resolve(rotated.body.token, ["services.saturn.sni"])).status, 200);
  await operator.delete(`/api/outdoor-tokens/${id}`);
  assert.equal((await resolve(rotated.body.token, ["services.saturn.sni"])).status, 401);
  assert.equal((await operator.post(`/api/outdoor-tokens/${id}/rotate`).send({})).status, 409);
});
